// MARK: - WARNING: GENERATED CODE
// GENERATED BY: SwiftPublicPackageStringsGenerator
// ---------------------------------------------------------------------------
// This file is auto-generated. Do not modify this file directly.
// Any changes made here will be lost when the generation process runs again.
// ---------------------------------------------------------------------------

import Foundation

public extension LocalizedStringResource {

    enum loc {
        public enum Common {
            public static let helloWorld: LocalizedStringResource = .helloWorld
            public static func helloWorldUserName(userName: String) -> LocalizedStringResource { .helloWorldUserName(userName: userName) }
            public static func teststringid(_ arg1: String) -> LocalizedStringResource { .testStringId(arg1) }
            public static let test: LocalizedStringResource = .TestCatalog.test
            public enum Second {
                public static let helloWorld: LocalizedStringResource = .SecondCatalog.helloWorld
            }
        }
    }    

}